# Фронтенд — calendar.local (порт 80)
server {
    listen 80;
    server_name calendar.local;

    location /storage {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
    }
    location /api {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin $http_origin;
        proxy_set_header Referer $http_referer;
    }
    location /sanctum {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin $http_origin;
        proxy_set_header Referer $http_referer;
    }
    location / {
        proxy_pass http://vue:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}

# Админка — admin.calendar.local (порт 80)
server {
    listen 80;
    server_name admin.calendar.local;

    location /storage {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
    }
    location /api {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Origin $http_origin;
        proxy_set_header Referer $http_referer;
    }
    location /sanctum {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Origin $http_origin;
        proxy_set_header Referer $http_referer;
    }
    location / {
        proxy_pass http://vue:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}

# Бэкенд Laravel — порт 8000
server {
    listen 8000;
    server_name calendar.local admin.calendar.local;
    root /var/www/html/public;
    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTP_ORIGIN $http_origin;
        fastcgi_param HTTP_REFERER $http_referer;
        include fastcgi_params;
    }
}